modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Creators-of-Create/Create/issues"
license="MIT"

[[mods]]
modId="create"
version="0.4.1"
displayName="Create"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/create"
logoFile="logo.png"
#credits=""
authors="simibubi"
description='''
Technology that empowers the player.'''

[[dependencies.create]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="flywheel"
    mandatory=true
    versionRange="[1.18-0.7.0,1.18-0.7.1)"
    ordering="AFTER"
    side="CLIENT"
