modLoader="javafml"
loaderVersion="[34,)"
#issueTrackerURL=""
license="MIT"

[[mods]]
modId="create"
version="${file.jarVersion}"
displayName="Create"
#updateJSONURL=""
authors="simibubi"
description='''
Technology that empowers the player.'''

[[dependencies.create]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.16,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="flywheel"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="AFTER"
    side="CLIENT"
