modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Creators-of-Create/Create/issues"
license="MIT"

[[mods]]
modId="create"
# The Implementation-Version property in the jar's MANIFEST.MF file will be used as the mod version at runtime
version="${file.jarVersion}"
displayName="Create"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/create"
logoFile="icon.png"
#credits=""
authors="simibubi"
description='''
Technology that empowers the player.'''

[[dependencies.create]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.10,0.6.11)"
    ordering="AFTER"
    side="CLIENT"
