modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Creators-of-Create/Create/issues"
license="MIT"

[[mods]]
modId="create"
version="v0.3.2e"
displayName="Create"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/create"
logoFile="logo.png"
#credits=""
authors="simibubi"
description='''
Technology that empowers the player.'''

[[dependencies.create]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="flywheel"
    mandatory=true
    versionRange="[1.16-0.2.3,1.16-0.3)"
    ordering="AFTER"
    side="BOTH"
