'version: 1.14':
    - '1\.14(?:\.\d)?'
'version: 1.15':
    - '1\.15(?:\.\d)?'
'version: 1.16':
    - '1\.16(?:\.\d)?'
'version: 1.17':
    - '1\.17(?:\.\d)?'
'version: 1.18':
    - '1\.18(?:\.\d)?'
'version: 1.19':
    - '1\.19(?:\.\d)?'
'version: 1.20':
    - '1\.20(?:\.\d)?'
